### PR TITLE
pl6env functionality and some cleanup

### PR DESCRIPTION
**Pull request by patzim**
Tested only on linux.
Currently the local version is determined by cwd and not the script location. I'll probably want to change that.
But Windows testing first.

### CODE REVIEW

**Comment by tadzik** [comment]
Merged it, keeping the "old rakudobrew" in "compat" branch, but I think we owe users some more deprecation notices, warnings and/or extra documentation. In addition to the fact that suddenly ```init``` is necessary for old users who upgraded, we now have commands that are a bit ambigous (I think) now that there's both ```local``` and ```global``` version: what does ```current``` mean now? And ```switch```? Should they become new-old names for ```global```, should they warn?

Let's regroup on IRC and think about it when you have a moment :)

**Comment by ugexe** [comment]
We need to be careful with changing core behavior like the `init` thing. Travis-CI for Perl6 uses rakudobrew, so most Perl6 projects started failing.

**Comment by ugexe** [comment]
`export PATH="$brew_path:\${PATH}"` is not windows compatable

**Comment by tadzik** [comment]
Oh, I wasn't aware of that. I guess Travis should stick to known-to-work rakudobrew version rather than pulling master and hoping it'll work.

As for windows, ```compat``` is the way to go for now, while the incompatibles are still there. I don't know anyone who uses rakudobrew on windows so I wasn't able to test/fix it.

**Comment by patzim** [comment]
I'm usually available Monday - Wednesday in the evenings.
I did not intend to break backwards compatibility. If I did, it's a bug. The new init is optional and only required for the new "shell" subcommand to function. All previously existing commands should continue to work as before without any change/init whatsoever.
It seems it *did* break though. Will look into it.

With respect to deprecation of previous commands I'm sightly leaning towards keeping the old ones.
It's basically being familiar to perlbrew/plenv vs being uniform and not duplicate commands.
If we decide to deprecate the old ones it would be consistent to also rename rakudobrew to pl6env.
It would also be possible to split and provide two commands rakudobrew and pl6env each with only the respective subcommands (with a slightly increased complexity).

**Pull request merged**
